name: Gerador A FAZENDA - TWITCH
on:
  schedule:
    - cron: '0 0/1 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Instalando yt-dlp 
      run: |
        sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp
    - name: Instalando youtube-dl 
      run: |
        sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl        
    - name: Instalando streamlink
      run: |
        sudo apt install ffmpeg python3-pip git
        pip install --user --upgrade streamlink
    - name: Atualizando youtube-dl
      run: |
        youtube-dl -U    
    - name: Instalando FFMpeg
      run: |
         sudo apt update
         sudo apt install ffmpeg
    
       
    - name: Get LISTA4.m3u8
      run: |
        touch ./AFAZENDA.m3u8
        sudo cat >./AFAZENDA.m3u8 <<EOL
        
        

        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(streamlink --url --default-stream  --stream-url  https://www.twitch.tv/fazenda14 best)
