name: Get VideoOFFAirSTR4
on:
  schedule:
    - cron: '* 19 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Instalando yt-dlp 
      run: |
        sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp
    - name: Get VideoOFFAirSTR4.m3u8
      run: |
        touch ./VideoOFFAir.m3u8
        sudo cat >./VideoOFFAir.m3u8 <<EOL               
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --get-url https://www.youtube.com/watch?v=D6ibf9rTA7E)
        EOL
           
    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "links atualizados"
        git push
