name: Get VideoOFFAirSTR2
on:
  schedule:
    - cron: '* 12 * * *'
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Instalando youtube-dl 
      run: |
        sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl 
    - name: Get VideoOFFAirSTR2.m3u8
      run: |
        touch ./VideoOFFAir.m3u8
        sudo cat >./VideoOFFAir.m3u8 <<EOL               
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --get-url https://www.youtube.com/watch?v=8KdWnyDnRZk)
        EOL
       

    - name: git add
      run: |
        git add -A
        ls -la
    - name: commit & push
      run: |
        git commit -m "links atualizados"
        git push
